### PR TITLE
[CALCITE-5077] ResetSession implements driver.SessionResetter. 

### PR DESCRIPTION
**Pull request by liguozhong**
avatica sql query fails after running for a period of time on our online loki, this PR attempts to solve this "NoSuchConnectionException" problem.

level=error ts=2022-03-31T12:51:09.356233496Z caller=table_manager.go:233 msg="error syncing tables" err="An error was encountered while processing your request: NoSuchConnectionException{connectionId='Connection not found: invalid id, closed, or expired: ccd95a16-5496-7001-f99b-1ab0e5f19e05'}"

### CODE REVIEW

**Comment by F21** [comment]
Can you amend the commit message? Please make it `[CALCITE-5077] ResetSession implements driver.SessionResetter`

**Comment by liguozhong** [comment]
> Can you amend the commit message? Please make it `[CALCITE-5077] ResetSession implements driver.SessionResetter`

done

**Comment by F21** [comment]
Just a small nit, can you remove the period at the end of the commit message?

**Comment by liguozhong** [comment]
> Just a small nit, can you remove the period at the end of the commit message?

done,thank you for your patience

**Pull request merged**
